/**
 * Compute the reference analysis from the shared landmark fixture.
 *
 * The JavaScript core is the source of this file; the Python test reads it back
 * and asserts its own numbers match. Regenerate with:
 *
 *   node tools/dump-metrics.mjs
 *
 * A change in the output is a change in what the app measures, so the diff on
 * this file is worth reading rather than waving through.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PoseSession, detectRacketArm } from '../web/js/core/session.js';
import { coachStroke, coachSession } from '../web/js/core/coach.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = join(here, '..', 'tests', 'fixtures');
const input = JSON.parse(readFileSync(join(fixtures, 'landmarks.json'), 'utf8'));

const session = new PoseSession({ racketArm: input.racket_arm });
for (const f of input.frames) {
  session.push({ t: f.t, world: f.world, image: f.image, frame: f.frame });
}

const round = (v, d = 6) => (Number.isFinite(v) ? Number(v.toFixed(d)) : null);

/** Every Nth frame's metrics: enough to catch drift without a huge file. */
const sampled = session.frames
  .filter((_, i) => i % 10 === 0)
  .map((f) => ({
    frame: f.frame,
    t: round(f.t),
    elbow: round(f.metrics.elbow),
    elbowOff: round(f.metrics.elbowOff),
    shoulderElevation: round(f.metrics.shoulderElevation),
    shoulderElevationOff: round(f.metrics.shoulderElevationOff),
    shoulderAzimuth: round(f.metrics.shoulderAzimuth),
    separation: round(f.metrics.separation),
    trunkLeanTotal: round(f.metrics.trunkLean.total),
    trunkLeanForward: round(f.metrics.trunkLean.forward),
    trunkLeanLateral: round(f.metrics.trunkLean.lateral),
    kneeLeft: round(f.metrics.kneeLeft),
    kneeRight: round(f.metrics.kneeRight),
    stanceWidth: round(f.metrics.stanceWidth),
    handHeight: round(f.metrics.hand.height),
    handLateral: round(f.metrics.hand.lateral),
    handForward: round(f.metrics.hand.forward),
    handExtension: round(f.metrics.hand.extension),
    trunkLength: round(f.metrics.trunkLength),
    armLength: round(f.metrics.armLength),
  }));

const strokes = session.strokes();
const armGuess = detectRacketArm(session.frames);

const payload = {
  note: 'Generated by tools/dump-metrics.mjs from tests/fixtures/landmarks.json. '
      + 'The Python parity test asserts its own numbers match these.',
  frameCount: session.frames.length,
  racketArm: session.racketArm,
  racketArmGuess: { arm: armGuess.arm, margin: round(armGuess.margin) },
  metrics: sampled,
  strokes: strokes.map((s) => ({
    index: s.index,
    frame: s.frame,
    t: round(s.t),
    shot: s.shot,
    side: s.side,
    height: s.height,
    confidence: round(s.confidence),
    peakSpeed: round(s.peakSpeed),
    peakSpeedMs: round(s.peakSpeedMs),
    startT: round(s.startT),
    endT: round(s.endT),
    contactElbow: round(s.contact.elbow),
    contactElevation: round(s.contact.shoulderElevation),
    contactHandHeight: round(s.contact.hand.height),
    contactHandLateral: round(s.contact.hand.lateral),
    contactHandForward: round(s.contact.hand.forward),
    contactTrunkLeanForward: round(s.contact.trunkLean.forward),
    backswingMinElbow: round(s.backswing.minElbow),
    backswingMaxSeparation: round(s.backswing.maxSeparation),
    backswingMaxOffArmElevation: round(s.backswing.maxOffArmElevation),
    windowMinKnee: round(s.window.minKnee),
  })),
  strokeCues: strokes.flatMap((s) => coachStroke(s)).map((c) => ({
    id: c.id, strokeIndex: c.strokeIndex, status: c.status, value: round(c.value),
  })),
  sessionCues: coachSession(session.frames, strokes).map((c) => ({
    id: c.id, status: c.status, value: round(c.value),
  })),
};

const target = join(fixtures, 'expected-metrics.json');
writeFileSync(target, `${JSON.stringify(payload, null, 1)}\n`);
process.stdout.write(`wrote ${target}\n`);
process.stdout.write(`  ${payload.metrics.length} sampled frames, `
  + `${payload.strokes.length} strokes, ${payload.strokeCues.length} cues\n`);
